title: "MasterControl Lead Scoring"
description: "MSBA IS 6813 Capstone · Spring 2026 · University of Utah"

show_downloads: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
